language: sh
os: osx
script:
  - python --version
  - python3 --version
  - git clone https://github.com/tableau/connector-plugin-sdk.git
  - cd connector-plugin-sdk
  - cd tdvt
  - ls
  - python -3 setup.py sdist --formats gztar
  - ls
  - python -3 -m pip install tdvt-1.5.15.zip
  - python -3 -m pip install -e .
  - python -3 -m pip list
