language: sh
os: osx
script:
  - python --version
  - python3 --version
  - git clone https://github.com/tableau/connector-plugin-sdk.git
  - cd connector-plugin-sdk
  - py -3 setup.py sdist --formats gztar
  - py -3 -m pip install tdvt-1.1.59.zip
  - py -3 -m pip install -e .
  - py -3 -m pip list
