language: sh
os: osx
script:
  - python --version
  - python3 --version
  - git clone https://github.com/tableau/connector-plugin-sdk.git
  - cd connector-plugin-sdk
  - cd tdvt
  - ls
  #- python -3 setup.py sdist --formats gztar
  #- find / -name tdvt-1.5.15
  #- python -3 -m pip install tdvt/tdvt-1.5.15.zip
  - python -3 -m pip install -e .
  - python -3 -m pip list
  - curl -o tableau.dmg https://downloads.tableau.com/tssoftware/TableauDesktop-2019-2-1.dmg
  - ls
  - sudo hdiutil attach tableau.dmg
  - sudo installer -package /Volumes/tableau/tableau.pkg
  - sudo hdiutil detach /Volumes/tableau
  - python -3 -m tdvt.tdvt --setup
