os: osx
sudo: false
#install:
before_script:
  - pg_ctl -D /usr/local/var/postgres start
  - createuser -s postgres
  - psql -c 'create database TestV1;' -U postgres
script:
  - python --version
  - python3 --version
# clone and install connector plugin
  - git clone https://github.com/tableau/connector-plugin-sdk.git
  - cd connector-plugin-sdk
  - cd tdvt
  - ls
  - python -3 -m pip install -e .
  - python -3 -m pip list
# download tableau desktop
  - curl -o tableau.dmg https://downloads.tableau.com/tssoftware/TableauDesktop-2019-2-1.dmg
  - ls
# mount and install dmg
  - sudo hdiutil attach tableau.dmg
  - sleep 10
  - sudo installer -pkg "/Volumes/Tableau Desktop/Tableau Desktop.pkg" -target /
# dismount the Tableau DMG volume
  - sudo hdiutil detach '/Volumes/Tableau Desktop'
  - pip3 install defusedxml
  - python3 -m tdvt.tdvt --setup
# postgres test
  - psql -c '\l' -U postgres
  - cat /Users/travis/build/peterhyvonen/OSXtesting/connector-plugin-sdk/tests/datasets/TestV1/postgres/load_batters.sql
  - python
  - import fileinput
  - with fileinput.FileInput(filename, inplace=True, backup='.bak') as file:
  - for line in file:
  - print(line.replace('<root_directory>', '/Users/travis/build/peterhyvonen/OSXtesting'), end='')
  - exit()
  - cat /Users/travis/build/peterhyvonen/OSXtesting/connector-plugin-sdk/tests/datasets/TestV1/postgres/load_batters.sql  
  - find / -name 'load_calcs.sql' 2>/dev/null
  - cat /Users/travis/build/peterhyvonen/OSXtesting/connector-plugin-sdk/tests/datasets/TestV1/postgres/load_calcs.sql
  - find / -name 'load_staples.sql' 2>/dev/null
  - cat /Users/travis/build/peterhyvonen/OSXtesting/connector-plugin-sdk/tests/datasets/TestV1/postgres/load_staples.sql
