language: sh
os: osx
before_script:
  - pg_ctl -D /usr/local/var/postgres start
  - psql -c 'create database mycooldb;'
script:
  - python --version
  - python3 --version
  # clone and install connector plugin
  - git clone https://github.com/tableau/connector-plugin-sdk.git
  - cd connector-plugin-sdk
  - cd tdvt
  - ls
  - python -3 -m pip install -e .
  - python -3 -m pip list
  # download tableau desktop
  - curl -o tableau.dmg https://downloads.tableau.com/tssoftware/TableauDesktop-2019-2-1.dmg
  - ls
  # mount and install dmg
  - sudo hdiutil attach tableau.dmg
  - sleep 10
  - sudo installer -pkg "/Volumes/Tableau Desktop/Tableau Desktop.pkg" -target /
  # dismount the Tableau DMG volume
  - sudo hdiutil detach '/Volumes/Tableau Desktop'
  - pip3 install defusedxml
  - python3 -m tdvt.tdvt --setup
